export const SUBJECT_LIST = [
  "Physics",
  "Chemistry",
  "Hindi",
  "English",
  "English Core",
  "Maths",
  "Biology",
  "Mathematics",
  "History",
  "Science",
  "Computer Applications",
  "Informatics",
  "Physical Education",
  "Applied Mathematics",
  "Applied Physics",
  "Social Science",
  "Engineering Mechanics",
  "Environmental",
  "Spoken",
  "Computer Programming",
  "Data Structures",
  "System Programming",
];
